package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Integer id;
     private Artista artista;
     private int anio;
     private String nombre;
     private Set cancions = new HashSet(0);

    public Album() {
    }

	
    public Album(int anio) {
        this.anio = anio;
    }
    public Album(Artista artista, int anio, String nombre, Set cancions) {
       this.artista = artista;
       this.anio = anio;
       this.nombre = nombre;
       this.cancions = cancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCancions() {
        return this.cancions;
    }
    
    public void setCancions(Set cancions) {
        this.cancions = cancions;
    }




}


