package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1



/**
 * ArtistaSeguidoId generated by hbm2java
 */
public class ArtistaSeguidoId  implements java.io.Serializable {


     private int idUsuario;
     private int idArtista;

    public ArtistaSeguidoId() {
    }

    public ArtistaSeguidoId(int idUsuario, int idArtista) {
       this.idUsuario = idUsuario;
       this.idArtista = idArtista;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(int idArtista) {
        this.idArtista = idArtista;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArtistaSeguidoId) ) return false;
		 ArtistaSeguidoId castOther = ( ArtistaSeguidoId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdArtista()==castOther.getIdArtista());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdArtista();
         return result;
   }   


}


