package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer id;
     private String genero;
     private String nombre;
     private Set conciertos = new HashSet(0);
     private Set albums = new HashSet(0);
     private Set artistaSeguidos = new HashSet(0);

    public Artista() {
    }

    public Artista(String genero, String nombre, Set conciertos, Set albums, Set artistaSeguidos) {
       this.genero = genero;
       this.nombre = nombre;
       this.conciertos = conciertos;
       this.albums = albums;
       this.artistaSeguidos = artistaSeguidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getConciertos() {
        return this.conciertos;
    }
    
    public void setConciertos(Set conciertos) {
        this.conciertos = conciertos;
    }
    public Set getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set albums) {
        this.albums = albums;
    }
    public Set getArtistaSeguidos() {
        return this.artistaSeguidos;
    }
    
    public void setArtistaSeguidos(Set artistaSeguidos) {
        this.artistaSeguidos = artistaSeguidos;
    }




}


