package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1



/**
 * ArtistaSeguido generated by hbm2java
 */
public class ArtistaSeguido  implements java.io.Serializable {


     private ArtistaSeguidoId id;
     private Artista artista;
     private Usuario usuario;

    public ArtistaSeguido() {
    }

    public ArtistaSeguido(ArtistaSeguidoId id, Artista artista, Usuario usuario) {
       this.id = id;
       this.artista = artista;
       this.usuario = usuario;
    }
   
    public ArtistaSeguidoId getId() {
        return this.id;
    }
    
    public void setId(ArtistaSeguidoId id) {
        this.id = id;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


