package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable {


     private Integer id;
     private Album album;
     private Subgenero subgenero;
     private String duracion;
     private float rating;
     private long reproducciones;
     private String titulo;
     private Set playlistCancions = new HashSet(0);

    public Cancion() {
    }

	
    public Cancion(float rating, long reproducciones) {
        this.rating = rating;
        this.reproducciones = reproducciones;
    }
    public Cancion(Album album, Subgenero subgenero, String duracion, float rating, long reproducciones, String titulo, Set playlistCancions) {
       this.album = album;
       this.subgenero = subgenero;
       this.duracion = duracion;
       this.rating = rating;
       this.reproducciones = reproducciones;
       this.titulo = titulo;
       this.playlistCancions = playlistCancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }
    public Subgenero getSubgenero() {
        return this.subgenero;
    }
    
    public void setSubgenero(Subgenero subgenero) {
        this.subgenero = subgenero;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public float getRating() {
        return this.rating;
    }
    
    public void setRating(float rating) {
        this.rating = rating;
    }
    public long getReproducciones() {
        return this.reproducciones;
    }
    
    public void setReproducciones(long reproducciones) {
        this.reproducciones = reproducciones;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getPlaylistCancions() {
        return this.playlistCancions;
    }
    
    public void setPlaylistCancions(Set playlistCancions) {
        this.playlistCancions = playlistCancions;
    }




}


