package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Concierto generated by hbm2java
 */
public class Concierto  implements java.io.Serializable {


     private Integer idConcierto;
     private Artista artista;
     private Date fecha;
     private String lugar;
     private String pais;

    public Concierto() {
    }

    public Concierto(Artista artista, Date fecha, String lugar, String pais) {
       this.artista = artista;
       this.fecha = fecha;
       this.lugar = lugar;
       this.pais = pais;
    }
   
    public Integer getIdConcierto() {
        return this.idConcierto;
    }
    
    public void setIdConcierto(Integer idConcierto) {
        this.idConcierto = idConcierto;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }




}


