package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1



/**
 * Entidades generated by hbm2java
 */
public class Entidades  implements java.io.Serializable {


     private Integer idEntidad;
     private String nombre;

    public Entidades() {
    }

    public Entidades(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(Integer idEntidad) {
        this.idEntidad = idEntidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


