package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String nombre;
     private Set subgeneros = new HashSet(0);

    public Genero() {
    }

    public Genero(String nombre, Set subgeneros) {
       this.nombre = nombre;
       this.subgeneros = subgeneros;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSubgeneros() {
        return this.subgeneros;
    }
    
    public void setSubgeneros(Set subgeneros) {
        this.subgeneros = subgeneros;
    }




}


