package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1



/**
 * PlaylistCancion generated by hbm2java
 */
public class PlaylistCancion  implements java.io.Serializable {


     private PlaylistCancionId id;
     private Cancion cancion;
     private Playlist playlist;

    public PlaylistCancion() {
    }

    public PlaylistCancion(PlaylistCancionId id, Cancion cancion, Playlist playlist) {
       this.id = id;
       this.cancion = cancion;
       this.playlist = playlist;
    }
   
    public PlaylistCancionId getId() {
        return this.id;
    }
    
    public void setId(PlaylistCancionId id) {
        this.id = id;
    }
    public Cancion getCancion() {
        return this.cancion;
    }
    
    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }
    public Playlist getPlaylist() {
        return this.playlist;
    }
    
    public void setPlaylist(Playlist playlist) {
        this.playlist = playlist;
    }




}


