package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Playlist generated by hbm2java
 */
public class Playlist  implements java.io.Serializable {


     private Integer idPlaylist;
     private Usuario usuario;
     private String nombre;
     private Set playlistCancions = new HashSet(0);

    public Playlist() {
    }

    public Playlist(Usuario usuario, String nombre, Set playlistCancions) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.playlistCancions = playlistCancions;
    }
   
    public Integer getIdPlaylist() {
        return this.idPlaylist;
    }
    
    public void setIdPlaylist(Integer idPlaylist) {
        this.idPlaylist = idPlaylist;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPlaylistCancions() {
        return this.playlistCancions;
    }
    
    public void setPlaylistCancions(Set playlistCancions) {
        this.playlistCancions = playlistCancions;
    }




}


