package ar.com.magm.ti.model;
// Generated 08/11/2017 23:33:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String contrasenia;
     private String mail;
     private String pais;
     private boolean premiun;
     private String usuario;
     private Set playlists = new HashSet(0);
     private Set artistaSeguidos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(boolean premiun) {
        this.premiun = premiun;
    }
    public Usuario(String contrasenia, String mail, String pais, boolean premiun, String usuario, Set playlists, Set artistaSeguidos) {
       this.contrasenia = contrasenia;
       this.mail = mail;
       this.pais = pais;
       this.premiun = premiun;
       this.usuario = usuario;
       this.playlists = playlists;
       this.artistaSeguidos = artistaSeguidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public boolean isPremiun() {
        return this.premiun;
    }
    
    public void setPremiun(boolean premiun) {
        this.premiun = premiun;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Set getPlaylists() {
        return this.playlists;
    }
    
    public void setPlaylists(Set playlists) {
        this.playlists = playlists;
    }
    public Set getArtistaSeguidos() {
        return this.artistaSeguidos;
    }
    
    public void setArtistaSeguidos(Set artistaSeguidos) {
        this.artistaSeguidos = artistaSeguidos;
    }




}


